# Generated by Django 3.2.3 on 2021-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('avatar', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
